databases:
  - name: inverse-staging-db
    plan: starter
  
services:
  - type: web
    name: frame-server-staging
    env: go
    region: oregon
    buildCommand: ./render-build.sh
    startCommand: ./frame-server
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: inverse-staging-db
          property: connectionString
      - key: NEYNAR_API_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_USER
        sync: false
      - key: BASE_URL
        sync: false
      - key: INVERSE_URL
        sync: false
      - key: KERNEL_FACTORY_ADDRESS
        sync: false
      - key: KERNEL_IMPLEMENTATION_ADDRESS
        sync: false
      - key: DEFAULT_VALIDATOR
        sync: false
      - key: RPC
        sync: false
